In [1]:
import dspy

# Konfiguration des lokalen Sprachmodells
local_llm = dspy.LM(
    "openai/gemma-3-4b-it-Q4_K_M.gguf", 
    api_base="http://localhost:8080/v1", 
    api_key="no_key_needed",
    temperature=0.1,
    cache=False
)

dspy.configure(lm=local_llm)

In [2]:
import heapq
from datasets import Dataset, load_dataset

# Lade die kürzesten Dokumente, da die längeren Dokumente nicht in das 128k Kontext Fenster des LLM passen
# Aber der Artikel muss mindestesn 10.000 Zeichen lang sein, da in dem Dataset doch einiges an Schrott drin ist :-(
def shortest_n(dataset, n, min_length=10000):
    """
    Wählt die n kürzesten Artikel aus, die mindestens `min_length` Zeichen lang sind.
    """
    # Filter auf Mindestlänge anwenden
    filtered = (x for x in dataset if len(x["article"]) >= min_length)
    
    # n kürzeste behalten
    return heapq.nsmallest(n, filtered, key=lambda x: len(x["article"]))

dataset = load_dataset("ccdv/arxiv-summarization", split="train")
shortest_125 = shortest_n(dataset, 125)
shortest_dataset = Dataset.from_list(shortest_125)

In [3]:
train_samples = shortest_dataset.select(range(100))
dev_samples = shortest_dataset.select(range(100, 125))

trainset = [dspy.Example(long_text=ex['article'], summary=ex['abstract']).with_inputs('long_text') for ex in train_samples]
devset = [dspy.Example(long_text=ex['article'], summary=ex['abstract']).with_inputs('long_text') for ex in dev_samples]

print(f"Anzahl der Beispiele im Trainingsset: {len(trainset)}")
print(f"Anzahl der Beispiele im Evaluationsset: {len(devset)}")

Anzahl der Beispiele im Trainingsset: 100
Anzahl der Beispiele im Evaluationsset: 25

In [4]:
# Diese mal sind die Sgnaturen auf englich, da das Dataset auch auf englisch ist und 
# die rouge_metric nur funktioniert, wenn wie Sprache von gold unf pred identisch ist.
class GenerateKeywords(dspy.Signature):
    """Generates a list of 10 relevant keywords from a long scientific text."""
    long_text = dspy.InputField(desc="A long scientific article from which keywords should be extracted.")
    keywords = dspy.OutputField(desc="A comma-separated list of 5–7 keywords.")

class SummarizeWithKeywords(dspy.Signature):
    """Creates a short summary of a scientific text while taking the provided keywords into account."""
    long_text = dspy.InputField(desc="The original scientific text.")
    keywords = dspy.InputField(desc="Relevant keywords that the summary should focus on.")
    summary = dspy.OutputField(desc="A concise summary of the article in 3–4 sentences.")

class SummarizationModule(dspy.Module):
    def __init__(self):
        super().__init__()
        self.keyword_generator = dspy.Predict(GenerateKeywords)
        self.summarizer = dspy.Predict(SummarizeWithKeywords)

    def forward(self, long_text):
        keywords_prediction = self.keyword_generator(long_text=long_text)
        summary_prediction = self.summarizer(long_text=long_text, keywords=keywords_prediction.keywords)
        return dspy.Prediction(summary=summary_prediction.summary)

In [5]:
# ROUGE-L ist eine Standardmetrik zur Bewertung von Zusammenfassungen.
import evaluate as hf_evaluate

rouge = hf_evaluate.load('rouge')

def rouge_metric(gold, pred, trace=None):
    """Berechnet den ROUGE-L F1-Score."""
    if not pred.summary or not gold.summary:
        return 0.0
    results = rouge.compute(predictions=[pred.summary], references=[gold.summary])
    return results['rougeL']

In [6]:
# Der Optimizer generiert für jeden Prädiktor im Modul bis zu 3 "Few-Shot"-Beispiele.
from dspy.teleprompt import BootstrapFewShot

optimizer = BootstrapFewShot(metric=rouge_metric, max_bootstrapped_demos=3)

# Der compile-Prozess wendet den Optimizer auf das Modul an.
print("\nBeginne die Kompilierung des Moduls. Dies kann einige Minuten dauern...")
compiled_summarizer = optimizer.compile(SummarizationModule(), trainset=trainset)
print("Kompilierung abgeschlossen.")

Beginne die Kompilierung des Moduls. Dies kann einige Minuten dauern...

  3%|███▍                                                                                                                | 3/100 [02:00<1:05:02, 40.24s/it]

Bootstrapped 3 full traces after 3 examples for up to 1 rounds, amounting to 3 attempts.
Kompilierung abgeschlossen.

In [7]:
# --- 6. Evaluation des unoptimierten und optimierten Moduls ---
from dspy.evaluate import Evaluate

evaluator = Evaluate(devset=devset, num_threads=1, display_progress=True, display_table=5)

print("\n--- Evaluation des unoptimierten Moduls (Zero-Shot) ---")
unoptimized_summarizer = SummarizationModule()
evaluator(unoptimized_summarizer, metric=rouge_metric)

print("\n--- Evaluation des optimierten Moduls (Few-Shot) ---")
evaluator(compiled_summarizer, metric=rouge_metric)

--- Evaluation des unoptimierten Moduls (Zero-Shot) ---
Average Metric: 5.15 / 25 (20.6%): 100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [03:31<00:00,  8.47s/it]

2025/11/13 19:34:53 INFO dspy.evaluate.evaluate: Average Metric: 5.154867295756456 / 25 (20.6%)

,long_text,example_summary,pred_summary,rouge_metric
0,"in the large scale region of wealth , income , profits , assets , ...",we investigate the dynamical behavior in the large scale region of...,This research investigates the dynamics of wealth distribution in ...,✔️ [0.234]
1,collective states constitute a significant part of the spectra of ...,the shell model monte carlo ( smmc ) approach allows for the micro...,This article discusses recent applications of the Shell Model Mont...,✔️ [0.287]
2,providing a repeatable movement is essential for a wide range of w...,when deploying a testbed infrastructure for wireless sensor networ...,Gondola is a novel robotic infrastructure designed to overcome lim...,✔️ [0.137]
3,"over the past decade , relativistic hydrodynamics has established ...",we show that in hydrodynamic simulations for relativistic heavy - ...,This research focuses on optimizing the hydro-to-hadron conversion...,✔️ [0.160]
4,the observations of mrk 501 in the very high energy ( ) domain wer...,the blazar markarian 501 ( mrk 501 ) was observed above 100 with t...,This study investigated the temporal and spectral variability of t...,✔️ [0.221]

--- Evaluation des optimierten Moduls (Few-Shot) ---
Average Metric: 5.56 / 25 (22.3%): 100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [34:11<00:00, 82.05s/it]

2025/11/13 20:09:04 INFO dspy.evaluate.evaluate: Average Metric: 5.562890051371735 / 25 (22.3%)

,long_text,example_summary,pred_summary,rouge_metric
0,"in the large scale region of wealth , income , profits , assets , ...",we investigate the dynamical behavior in the large scale region of...,this study investigates the dynamical behavior of non-equilibrium ...,✔️ [0.280]
1,collective states constitute a significant part of the spectra of ...,the shell model monte carlo ( smmc ) approach allows for the micro...,the shell model monte carlo ( smmc ) method has been successfully ...,✔️ [0.274]
2,providing a repeatable movement is essential for a wide range of w...,when deploying a testbed infrastructure for wireless sensor networ...,"we present gondola, a novel robotic infrastructure for wireless se...",✔️ [0.176]
3,"over the past decade , relativistic hydrodynamics has established ...",we show that in hydrodynamic simulations for relativistic heavy - ...,this paper outlines a strategy to improve the accuracy of anisotro...,✔️ [0.163]
4,the observations of mrk 501 in the very high energy ( ) domain wer...,the blazar markarian 501 ( mrk 501 ) was observed above 100 with t...,during the observation campaign of mrk 501 between may and july 20...,✔️ [0.205]

EvaluationResult(score=22.25, results=<list of 25 results>)

In [8]:
# --- 7. Inspektion der optimierten Prompts ---
print("\n--- Inspektion eines optimierten Prompts ---")
# Ein Beispieldurchlauf, um die internen Prompts zu inspizieren.
example_dev_text = devset[0].long_text
compiled_summarizer(long_text=example_dev_text)

--- Inspektion eines optimierten Prompts ---

Prediction(
    summary='this study investigates the dynamical behavior of non-equilibrium systems in the large scale region of wealth using data on assessed land values in Japan from 1983 to 2006. \n it identifies a detailed quasi-balance, derived from gibrat’s law and the detailed balance, which allows for the derivation of a varying pareto index over time. \n the analysis reveals a significant shift in the pareto index between 1984 and 1986, indicating a period of rapid change in the system’s dynamics, and highlights the differences between the large and middle scale regions of economic distribution.'
)

In [9]:
# Inspektion des letzten Prompts, der an den 'summarizer' Prädiktor gesendet wurde.
local_llm.inspect_history(n=1)

[2025-11-13T20:17:28.665959]

System message:

Your input fields are:
1. `long_text` (str): The original scientific text.
2. `keywords` (str): Relevant keywords that the summary should focus on.
Your output fields are:
1. `summary` (str): A concise summary of the article in 3–4 sentences.
All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## long_text ## ]]
{long_text}

[[ ## keywords ## ]]
{keywords}

[[ ## summary ## ]]
{summary}

[[ ## completed ## ]]
In adhering to this structure, your objective is:
        Creates a short summary of a scientific text while taking the provided keywords into account.


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## long_text ## ]]
the study of domain walls ( dw ) magnetic ( static and dynamic ) @xcite and transport @xcite properties have attracted much attention recently due to their relevance for magneto - electronic nano - device applications . in the static case ,
 mcmichael and donahue have shown that in magnetic stripes head - to - head dw can be in vortex or transverse shape @xcite .
 et al . _ have observed these dw structures in magnetic thin films and rings @xcite .  in this work ,
 we study the dynamics of dw with magnetization mostly restricted to the plane of a nanometer - size thin film
 .   dw motion can be a source of low frequency noise in magnetic systems and thus hinder any potential applications .
 their high frequency behavior can however be tuned by choosing suitable boundary conditions or geometries .
 constrained dw oscillations can be high in frequency and hence there is a potential for their use in nano - electronics as resonators @xcite .
 at least two modes of oscillations have been studied in the literature ; a doring - type oscillation and a winter mode oscillation @xcite . the doring mode is associated with translations of the center of mass of the dw in an infinite system , while the winter modes are non - zero energy modes that , in addition to rigid translation , correspond to propagations along the dw .
 these modes are found by solving the time - dependent landau - lifshitz ( ll ) equations @xcite .    in the following ,
 we focus only on dynamical properties of transverse _ tail - to - tail _ dw trapped in stripes with dimensions comparable to their width . this case
 is proved to be the most interesting due to the unusual magnetization dynamics as opposed to the conventional case of dw with widths being much smaller than the film size .
 in particular , we find that the low frequency excitations can be reduced in comparison with the usual cpp configuration having a uniform magnetization .
 such uniform magnetization is susceptible to large fluctuations due to spin momentum transfer and gives rise to appreciable @xmath0-like noise .
 @xcite we investigate dw formed by pinning the magnetization in the opposite directions at the edges along the easy axis .
 we show that dw motion can be controlled by a current perpendicular to the plane of the dw magnetization in contrast with the currently actively studied case of dw motion in nano - wires .
 @xcite    the ll equation is the basis for the present study .
 since , we are looking at thermal and current effects , a random field and a spin torque term are also added to the ll equation@xcite .
 we show that in the spin valve ( sv ) geometry suggested here the spin torque can provide the force needed to move the wall in a controlled fashion with @xmath1 times smaller current values than those needed to switch the uniform magnetization in a cpp sv .
 the paper is organized as follows .  in section [ sec : background ]
 we describe both the theoretical background and the computational model needed for our study .  in section [ sec :
 modes ] , we discuss the dw structure and we also calculate the lowest eigenmodes of the dw using a simple one dimensional model and compare it to the numerical solution .  it is shown that if the center of the dw is allowed to drift along the easy axis , the contribution to the 1/f - type noise increases .  in section [ subsec : spz ] , we study the effect of an external field and a cpp current on the sv with and without dw .  we find that sv with a uniform magnetization can be susceptible to unwanted behavior due the spin torque driven instabilities that are absent in a sv with a constrained dw .
 we consider a new cpp geometry with a constrained dw between two fixed layers one pinned along and the other pinned perpendicular to the direction of the current flow . we find that in this cpp structure the dw motion can be well controlled with current densities which do not lead to the magnetization instabilities .
 it is shown that accurate quantification of demagnetizing fields is not essential for a qualitative understanding of the influence of the spin torque on the dw .  in section [ sec : summ - conc ] , we summarize our results .
 for a magnetization @xmath2 with magnitude @xmath3 , the ll equation for @xmath4 with a damping in the gilbert form and time normalized by @xmath5 , where @xmath6 is the gyromagnetic ratio , is given by @xcite    @xmath7    where the effective field @xmath8 includes the exchange interaction , the anisotropy field along the @xmath9 axis , the demagnetization field , the oersted field , and the spin torque @xmath10 the damping term is taken to be @xmath11 in the absence of currents and is increased to @xmath12 in the presence of spin torques to account for spin accumulation at the normal - ferromagnetic interface . the exchange constant @xmath13 in this study .
 the random field @xmath14 is taken to be uniform and gaussian white at temperature @xmath15 , @xmath16 .
 @xcite  in the presence of spin torques , the white noise assumption @xcite is strictly valid only for frequencies around the resonant frequency as shown in ref . .
 since we are only interested in currents below the critical current , the white noise assumption will not alter the qualitative conclusions of this work .
 the size of the discretized cell is taken @xmath17 in the plane of the film .
 the inclusion of the demagnetizing field is important in dw motion studies and hence a numerical treatment is often needed to get a quantitative understanding of the dynamics of a dw @xcite .  the last term in eq .
 [ eq : heff ] is the contribution of a spin torque from the pinned layer ( pl ) @xmath18 .
 the prefactor @xmath19 is dependent of geometrical parameters and @xmath20 is the current flowing perpendicular to the magnetic multi - layers .  the @xmath19 prefactor is dependent on the thickness @xmath21 , the cross section @xmath22 of the layer and the polarization of the current .
 assuming perfect polarization of the conduction electrons , with charge @xmath23 , by the reference layer and neglecting the angular dependence dependence , the spin torque coefficient is given by @xmath24 in the following simulations , the anisotropy field is taken @xmath25 and the saturated magnetization is @xmath26 .
 in this section , we introduce the geometry of the dw and study its excitation modes compared to those generated in the uniform case .
 we show that the in - plane components of the magnetizations have distinctly different lowest mode frequencies that are directly related to the inhomogeneities of the magnetization due to the dw .
 we also discuss the magnetization evolution if we remove the pinning boundary conditions and allow dw to relax to the uniform magnetization state .
 in addition to the zero temperature dynamics , we investigate the effect of thermal fluctuations on the motion of transverse dw .
 [ cols= " < , < " , ]
 in summary , we have presented a study of magnetization dynamics for cpp geometry which includes a constrained dw layer .
 we have identified a doring - type mode and a new breathing mode .
 it is shown that the lowest modes of the dw dynamics can be understood in terms of the parity of the inhomogeneous ground state .
 we have investigated in details how the constrained dw dynamics is affected by the spin polarized current and thermal fluctuations and compared it with the traditional single domain free layer structures .
 in particular , we found that the currents needed to measure any appreciable motion of the dw are at least two orders of magnitude less than usual values of currents needed to switch the single domain magnetization .
 this difference is attributed to the appearance of a significant magnetization component of the constrained dw that is perpendicular to the pinned layer magnetization and the exchange field .
 we also find that thermally activated motion of the constricted dw has lower weight in the lower frequency region than that of the unconstrained dw .
 the latter shows well known telegraph type noise characteristics .
 this difference can be understood using notion of charged dw introduced by neel @xcite and competition of the magnetostatic and size dependent exchange interaction contributions to the dw potential for motion along the easy axis ( see fig .
 [ demag ] ) .
 the three magnetic layer cpp structure was introduced so that the spin torque effect on dw layer is maximized .
 this cpp geometry has been investigated and found to have a number of interesting properties such as ( i ) dw can be easily controlled by an external field or a polarized current with relatively small current densities ; ( ii ) linear dependence of resistance on the external field and current ; ( iii ) improved magnetization stability characteristics .
 experimental realization of the device proposed here requires finding ways to constrain the dw within the middle free layer .
 the pinning at the edges can be realized by creating permanent magnets with different coercivity and/or with anti - ferromagnetic ( af ) coupling .
 the af coupling at the edges needs antiferromagnets with different neel temperatures @xcite so that a properly designed field - cooling procedure could lead to the pinning in opposite directions at the edges of the magnetic stripe .
 other alternatives such as special shaping and padding also have been discussed in the literature in the context of stability of dw in magnetic nano - elements @xcite .
 we thank g. parker for making his llg solver available to us .
 p. asselin and w. scholz have provided us with many helpful comments on the text .
 we also acknowledge helpful discussions with t. ambrose , l. berger and m. covington .
 m. klaui , h. ehrke , u. rudiger , t. kasama , r. e. durin - borkowski , d. backes , l. j. heyderman , c. a. f. vaz , j.a . c. bland , g. faini , e. cambril , and w. wernsdorfer , appl .
 . lett . * 87 * , 102509 ( 2005 ) .


Assistant message:

[[ ## summary ## ]]
a study of transverse tail - to - tail magnetic domain walls ( dw ) in novel current perpendicular to the plane ( cpp ) spin valves ( sv ) of various dimensions is presented . for films with dimensions larger than the dw width
 , we find that dw motion can give rise to a substantial low frequency noise . for dimensions comparable to the dw width
 , we show that the dw can be controlled by an external field or by a spin momentum torque as opposed to the case of cpp - sv with uniform magnetization .
 it is shown that in a single domain biased cpp - sv , the spin torque can give rise to 1/f - type noise . the dipolar field ,
 the spin torque and the oersted field are all accounted for in this work .
 our proposed sv requires low current densities to move dw and can simulate devices for logical operation or magnetic sensing without having to switch the magnetization in the free layer .

[[ ## completed ## ]]


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## long_text ## ]]
when probing small distances inside a hadron with a fixed momentum scale @xmath2 one resolves its constituents quarks and gluons .
 as one increases the energy of the scattering process , the parton densities seen by the probe grow . at some energy much bigger than the hard scale
 , the gluon density has grown so large that non - linear effects become important .
 one enters the saturation regime of qcd , a non - linear yet weakly - coupled regime that describes the hadron as a dense system of weakly interacting partons ( mainly gluons ) .
 the transition to the saturation regime is characterized by the so - called saturation momentum @xmath3 this is an intrinsic scale of the high - energy hadron which increases as @xmath4 decreases . @xmath5 but as the energy increases , @xmath6 becomes a hard scale , and the transition to saturation occurs when @xmath6 becomes comparable to @xmath7 although the saturation regime is only reached when @xmath8 observables are sensitive to the saturation scale already during the approach to saturation when @xmath9 this is especially true in the case of hard diffraction in deep inelastic scattering ( dis ) .    both inclusive ( @xmath10 ) and diffractive ( @xmath11 )
 dis are processes in which a photon ( of virtuality @xmath12 ) is used as the hard probe , and at small values of @xmath13 parton saturation becomes relevant .
 the dipole picture naturally describes inclusive and diffractive events within the same theoretical framework .
 it expresses the scattering of the virtual photon through its fluctuation into a color singlet @xmath14 pair ( or dipole ) of a transverse size @xmath15 .
 the dipole is then what probes the target proton , seen as a color glass condensate ( cgc ) : a dense system of gluons that interact coherently .
 therefore , despite its perturbative size , the dipole cross - section is comparable to that of a pion .
 the same dipole scattering amplitude @xmath16 enters in the formulation of the inclusive and diffractive cross - sections : @xmath17 where @xmath18 is the well - known @xmath19 wavefunction . to obtain the right - hand sides
 , we have decomposed the dipole - size integration into three domains : @xmath20 @xmath21 and @xmath22 and used the dipole amplitude @xmath16 discussed below .
 one sees that hard diffractive events ( @xmath23 ) are much more sensitive to saturation than inclusive events , as the contribution of small dipole sizes is suppressed and the dominant size is @xmath24
 the good - and - walker picture of diffraction was originally meant to describe soft diffraction .
 they express an hadronic projectile @xmath25 in terms of hypothetic eigenstates of the interaction with the target @xmath26 that can only scatter elastically : @xmath27 the total , elastic and diffractive cross - sections are then easily obtained : @xmath28 ^ 2\hspace{0.5 cm } \sigma_{diff}=\sum_n c_n^2 t_n^2\ .\label{gaw}\ ] ]    it turns out that in the high energy limit , there exists a basis of eigenstates of the large@xmath29 qcd @xmath30matrix : sets of quark - antiquark color dipoles @xmath31 characterized by their transverse sizes @xmath32 in the context of deep inelastic scattering ( dis ) , we also know the coefficients @xmath33 to express the virtual photon in the dipole basis . for instance , the equivalent of @xmath34 for the one - dipole state is the photon wavefunction @xmath35    r0.5        this realization of the good - and - walker picture allows to write down exact ( within the high - energy and large@xmath29 limits ) factorization formulae for the total and diffractive cross - sections in dis . they are expressed in terms of elastic scattering amplitudes of dipoles off the cgc @xmath36 where @xmath37 is the total rapidity .
 the average @xmath38 is an average over the cgc wavefunction that gives the energy dependence to the cross - sections .
 formulae are similar to ( [ gaw ] ) with extra integrations over the dipoles transverse coordinates .
 for instance , denoting the minimal rapidity gap @xmath39 the diffractive cross - section reads  @xcite @xmath40 this factorization is represented in fig .
 [ ddis ] . besides the @xmath12 dependence
 , the probabilities to express the virtual photon in the dipole basis @xmath41 also depend on @xmath42 starting with the initial condition @xmath43 the probabilities can be obtained from the high - energy qcd rapidity evolution .
 finally , the scattering amplitude of the n - dipole state @xmath44 is given by @xmath45 where @xmath46 is the scattering amplitude of the one - dipole state .
 the rapidity evolution of the correlators @xmath47 should obtained from the cgc non - linear equations ; one can then compute the diffractive cross - section .    when taking @xmath48 in formula , one recovers the formula used for our previous estimates , which corresponds to restricting the diffractive final state to a @xmath14 pair . in practice
 the description of hera data also requires a @xmath49 contribution .
 within the high - energy and large@xmath29 limits , the scattering amplitudes off the cgc are obtained from the pomeron - loop equation  @xcite derived in the leading logarithmic approximation in qcd .
 this is a langevin equation which exhibits the stochastic nature  @xcite of high - energy scattering processes in qcd .
 its solution @xmath50 is an event - by - event dipole scattering amplitude function of @xmath51 and @xmath52 ( @xmath53 is a scale provided by the initial condition ) .    r0.5        the solution @xmath54 is characterized by a saturation scale @xmath6 which is a random variable whose logarithm is distributed according to a gaussian probability law  @xcite .
 the average value is @xmath55 and the variance is @xmath56 the saturation exponent @xmath57 determines the growth of @xmath58 with rapidity , and the dispersion coefficient @xmath59 defines two energy regimes : the geometric scaling regime ( @xmath60 ) and diffusive scaling regime ( @xmath61 ) .
 evolving a given initial condition yields a stochastic ensemble of solutions @xmath62 from which one obtains the dipole correlators : @xmath63 where in the right - hand side , @xmath64 is an average over the realizations of @xmath65 indeed , both quantities @xmath66 and @xmath67 obey the same hierarchy of equations .
 one obtains the following results for the dipole scattering amplitudes  @xcite : @xmath68 all the scattering amplitudes are expressed in terms of @xmath69 the amplitude for a single dipole which features the following scaling behaviors : @xmath70    in the saturation region @xmath71 @xmath72 as the dipole size @xmath73 decreases , @xmath74 decreases towards the weak - scattering regime following the scaling laws ( [ gs ] ) or ( [ ds ] ) , depending on the value of @xmath75 as shown in fig .
 [ ploop ] . in the geometric scaling regime ( @xmath60 )
 , the dispersion of the events is negligible and the averaged amplitude obeys ( [ gs ] ) . in the diffusive scaling regime ( @xmath61 ) , the dispersion of the events is important , resulting in the behavior ( [ ds ] ) .
 when pomeron loops are not included in the evolution , only the geometric scaling regime appears .
 in the geometric scaling regime , instead of being a function of the two variables @xmath73 and @xmath76 @xmath77 is a function of the single variable @xmath78 up to inverse dipole sizes significantly larger than the saturation scale @xmath79 this means that in the geometric scaling window in fig .  [ ploop ] , @xmath77 is constant along lines parallel to the saturation line .
 physically , they are lines along which the dipole sees a constant partonic density inside the proton .    in dis
 , this feature manifests itself via the so - called geometric scaling property . instead of being a function of @xmath12 and @xmath4 separately ,